device: cpu
eval_metric:
  name: BoundaryAdaptedRandError
  threshold: 0.4
  use_first_input: true
  use_last_target: true
loaders:
  label_internal_path: /label
  num_workers: 8
  raw_internal_path: /raw
  train:
    file_paths:
    - /home/thodkatz/repos/kreshuklab/ilastik-playground/tiktorch_playground/3d_unet_lightseet_boundary/data/train/Movie1_t00009_crop_gt.h5
    slice_builder:
      name: FilterSliceBuilder
      patch_shape:
      - 80
      - 170
      - 170
      slack_acceptance: 0.01
      stride_shape:
      - 20
      - 40
      - 40
      threshold: 0.6
    transformer:
      label:
      - name: RandomFlip
      - name: RandomRotate90
      - angle_spectrum: 45
        axes:
        - - 2
          - 1
        mode: reflect
        name: RandomRotate
      - name: ElasticDeformation
        spline_order: 0
      - append_label: true
        name: StandardLabelToBoundary
      - expand_dims: false
        name: ToTensor
      raw:
      - name: Standardize
      - name: RandomFlip
      - name: RandomRotate90
      - angle_spectrum: 45
        axes:
        - - 2
          - 1
        mode: reflect
        name: RandomRotate
      - name: ElasticDeformation
        spline_order: 3
      - execution_probability: 0.5
        name: GaussianBlur3D
      - execution_probability: 0.2
        name: AdditiveGaussianNoise
      - execution_probability: 0.2
        name: AdditivePoissonNoise
      - expand_dims: true
        name: ToTensor
  val:
    file_paths:
    - /home/thodkatz/repos/kreshuklab/ilastik-playground/tiktorch_playground/3d_unet_lightseet_boundary/data/val/N_464_ds2x.h5
    slice_builder:
      name: FilterSliceBuilder
      patch_shape:
      - 80
      - 170
      - 170
      slack_acceptance: 0.01
      stride_shape:
      - 80
      - 170
      - 170
      threshold: 0.6
    transformer:
      label:
      - append_label: true
        name: StandardLabelToBoundary
      - expand_dims: false
        name: ToTensor
      raw:
      - name: Standardize
      - expand_dims: true
        name: ToTensor
loss:
  ignore_index: null
  name: BCEDiceLoss
  skip_last_target: true
lr_scheduler:
  factor: 0.2
  mode: min
  name: ReduceLROnPlateau
  patience: 20
model:
  f_maps: 32
  final_sigmoid: true
  in_channels: 1
  layer_order: gcr
  name: ResidualUNet3D
  num_groups: 8
  out_channels: 1
optimizer:
  learning_rate: 0.0002
  weight_decay: 1.0e-05
trainer:
  checkpoint_dir: ./model_resources
  eval_score_higher_is_better: false
  log_after_iters: 500
  max_num_epochs: 1000
  max_num_iterations: 150000
  pre_trained: null
  resume: null
  validate_after_iters: 1000
